### ISSUE TITLE
Password after "vagrant ssh" and other box comments

### ISSUE THREAD

**Issue by shponny** [RomanAvseenko/devops-lab01#4]
1. После `vagrant ssh vm-xx` CentOS требует пароль пользователя vagrant.
2. Рекомендую подкорректировать боксы - установить без GUI для улучшения производительности - с GUI система даже swap задействовала.

**Comment by roman-avseenko** [comment]
- Протестил при различных условиях `vagrant ssh vm-xx`, запроса пароля не выявил
- Боксы пересобрал, система запускается без GUI
